export const LeadingInvestors = [
  { src: "../images/logo-palantir.png" },
  { src: "../images/coatue-logo.png" },
  { src: "../images/investor-logo.svg" },
  { src: "../images/logo-palantir.png" },
  { src: "../images/coatue-logo.png" },
  { src: "../images/investor-logo.svg" },
  { src: "../images/logo-palantir.png" },
  { src: "../images/coatue-logo.png" },
  { src: "../images/investor-logo.svg" },
  { src: "../images/logo-palantir.png" },
  { src: "../images/coatue-logo.png" },
  { src: "../images/investor-logo.svg" },
  { src: "../images/logo-palantir.png" },
  { src: "../images/coatue-logo.png" },
  { src: "../images/investor-logo.svg" },
];
